@startuml
'https://plantuml.com/sequence-diagram

autonumber
支付 -> 渠道 : 打款申请
渠道 -> 渠道 : 查询商户号和渠道
渠道 -> 渠道数据库 : 查看有无此单款单
渠道数据库 --> 渠道 : 打款单不存在
渠道 -> 渠道数据库 : 创建并初始化打款单
渠道 -> 第三方 : 调用第三方打款
第三方 --> 渠道 :返回成功
渠道 --> 支付 : 打款单创建成功

@enduml