@startuml
'https://plantuml.com/sequence-diagram

autonumber

支付系统 -> 渠道系统 : 申请退款
渠道系统 -> 渠道系统 : 参数校验
渠道系统 -> 渠道数据库 : 查询有无此退款单
渠道数据库 --> 渠道系统 : 无此退款单，有此支付单
渠道系统 -> 渠道数据库 : 创建退款单并初始化
渠道系统 -> 第三方支付机构 : 调用第三方机构退款
第三方支付机构 --> 渠道系统 : 返回成功
渠道系统 --> 支付系统 : 通知退款单创建成功


@enduml