@startuml

autonumber

第三方机构 -> 渠道 : http支付回调
渠道 -> 渠道 : 参数校验
渠道 -> 渠道数据库 : 查看是否存在此单
渠道 <-- 渠道数据库 : 存在非终态且金额正确的支付单
渠道 -> 渠道数据库 : 更新此单为SUCCESS
渠道 -> 支付 : 通知支付系统
支付 --> 渠道 : 返回成功
渠道 --> 第三方机构 : 拼接响应，告知第三方机构





@enduml