@startuml

autonumber

第三方机构 -> 渠道 : http退款回调
渠道 -> 渠道 : 验证参数
渠道 -> 渠道数据库 : 查看有无此非终态的退款单
渠道数据库 --> 渠道 : 存在非终态的退款单
渠道 -> 渠道数据库 : 将此单修改为中台 SUCCESS
渠道 -> 支付 : 通知支付系统
支付 --> 渠道 : 返回成功
渠道 --> 第三方机构 : 拼接响应，通知第三方

@enduml